# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropy <- function(p) {
    .Call(`_spartropy_entropy`, p)
}

entropy2 <- function(p) {
    .Call(`_spartropy_entropy2`, p)
}

entropy10 <- function(p) {
    .Call(`_spartropy_entropy10`, p)
}

mutual_information2 <- function(ps) {
    .Call(`_spartropy_mutual_information2`, ps)
}

frequencies <- function(x) {
    .Call(`_spartropy_frequencies`, x)
}

normalise <- function(x) {
    .Call(`_spartropy_normalise`, x)
}

matrix_subset <- function(x, y) {
    .Call(`_spartropy_matrix_subset`, x, y)
}

frequencies_2d <- function(x, is, js) {
    .Call(`_spartropy_frequencies_2d`, x, is, js)
}

normalise_2d <- function(x) {
    .Call(`_spartropy_normalise_2d`, x)
}

mutual_information_implicit <- function(x, is, js) {
    .Call(`_spartropy_mutual_information_implicit`, x, is, js)
}

mutual_information2_implicit <- function(x, is, js) {
    .Call(`_spartropy_mutual_information2_implicit`, x, is, js)
}

mutual_information10_implicit <- function(x, is, js) {
    .Call(`_spartropy_mutual_information10_implicit`, x, is, js)
}

