# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropyE_ <- function(p) {
    .Call(`_spartropy_entropyE_`, p)
}

entropy2_ <- function(p) {
    .Call(`_spartropy_entropy2_`, p)
}

entropy10_ <- function(p) {
    .Call(`_spartropy_entropy10_`, p)
}

mutual_informationE_ <- function(ps) {
    .Call(`_spartropy_mutual_informationE_`, ps)
}

mutual_information2_ <- function(ps) {
    .Call(`_spartropy_mutual_information2_`, ps)
}

mutual_information10_ <- function(ps) {
    .Call(`_spartropy_mutual_information10_`, ps)
}

frequencies_ <- function(x) {
    .Call(`_spartropy_frequencies_`, x)
}

normalise_ <- function(x) {
    .Call(`_spartropy_normalise_`, x)
}

frequencies_2d_ <- function(x, is, js) {
    .Call(`_spartropy_frequencies_2d_`, x, is, js)
}

normalise_2d_ <- function(x) {
    .Call(`_spartropy_normalise_2d_`, x)
}

mutual_informationE_implicit_ <- function(x, is, js) {
    .Call(`_spartropy_mutual_informationE_implicit_`, x, is, js)
}

mutual_information2_implicit_ <- function(x, is, js) {
    .Call(`_spartropy_mutual_information2_implicit_`, x, is, js)
}

mutual_information10_implicit_ <- function(x, is, js) {
    .Call(`_spartropy_mutual_information10_implicit_`, x, is, js)
}

